// Converge integration for opencode. Generated by `converge init` —
// edits are lost on the next run; the source is in converge-cli.
//
// opencode has no hook commands, so this plugin is the shim: it turns
// plugin callbacks into the same `converge hook …` entrypoints every
// other harness invokes directly, and applies the answer back.
//
// __CONVERGE_BIN__ is replaced with an absolute path at install time.

import { execFile } from "node:child_process";

const CONVERGE = "__CONVERGE_BIN__";

// Sessions whose context block has already been injected. opencode has
// no session-start event: the closest hook fires before *every* request,
// so without this the decision index would be re-injected each turn.
const injected = new Set();

/// Feed a payload to an entrypoint and parse whatever it says back.
/// Never throws and never blocks the agent: a converge problem must not
/// break someone's session, so failure is silence.
function hook(sub, payload) {
  return new Promise((resolve) => {
    let child;
    try {
      child = execFile(
        CONVERGE,
        ["hook", sub, "--harness", "opencode"],
        { timeout: 10_000, maxBuffer: 8 << 20 },
        (error, stdout) => {
          if (error) return resolve(null);
          try {
            resolve(JSON.parse(stdout));
          } catch {
            resolve(null);
          }
        },
      );
    } catch {
      return resolve(null);
    }
    child.stdin.on("error", () => resolve(null));
    child.stdin.end(JSON.stringify(payload));
  });
}

// Which tools are ours. The MCP server is registered under the name
// `converge`, and opencode composes tool ids from the server name, so
// the name is in the id whatever separator it picks. Matching the
// substring rather than a guessed `converge_x` / `mcp__converge__x`
// spelling means this keeps working if that spelling changes.
const isOurs = (tool) => typeof tool === "string" && tool.includes("converge");
const isBinding = (tool) =>
  isOurs(tool) && (tool.endsWith("project_bind") || tool.endsWith("project_dismiss"));

export const server = async ({ directory }) => ({
  // Session start, as close as opencode gets to one.
  "experimental.chat.system.transform": async (input, output) => {
    const session = input.sessionID;
    if (!session || injected.has(session)) return;
    injected.add(session);
    const said = await hook("inject", { cwd: directory, session_id: session });
    if (said && said.context) output.system.push(said.context);
  },

  // Pre-tool: hand the server cwd and git remote so it can rank project
  // candidates without the model gathering anything.
  "tool.execute.before": async (input, output) => {
    if (!isOurs(input.tool)) return;
    const said = await hook("ctx", {
      cwd: directory,
      session_id: input.sessionID,
      tool_input: output.args,
    });
    if (said && said.tool_input && typeof said.tool_input === "object") {
      Object.assign(output.args, said.tool_input);
    }
  },

  // Post-tool: the local effect. The marker is written by converge, not
  // by the model, so a binding is deterministic.
  "tool.execute.after": async (input, output) => {
    if (!isBinding(input.tool)) return;
    await hook("mark", {
      cwd: directory,
      session_id: input.sessionID,
      tool_response: output.output,
    });
  },

  // Evidence. opencode has no session-end event either; `session.idle`
  // is every lull, which is fine — sync is incremental by watermark, so
  // syncing often costs nothing and loses less than syncing once would.
  event: async ({ event }) => {
    if (!event || event.type !== "session.idle") return;
    const session = event.properties && event.properties.sessionID;
    if (!session) return;
    await hook("sync", { cwd: directory, session_id: session });
  },
});
